# .github/workflows/my-workflow.yml
name: My Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'production'
        options:
          - production
          - staging
          - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: echo "Running in environment: ${{ github.event.inputs.environment }}"
