name: My Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'production'
      tf_apply:
        description: 'apply'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: |
          echo "Running in environment: ${{ github.event.inputs.environment }}"
          echo "Apply : ${{ github.event.inputs.tf_apply }}"
